[[mgr.prepend_keymap]]
on = ['g', 'r']
run = 'cd /media/linuxhdd/RoseHulman/'
desc = "Go to Rose folder"

[[mgr.prepend_keymap]]
on = ['g', 'm']
run = 'cd /media/linuxhdd/Media/'
desc = 'Go to Media folder'

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

# MOUNT
[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"
