[[mgr.prepend_keymap]]
on = ['g', 'r']
run = 'cd ~/linuxhdd/RoseHulman/'
desc = "Go to Rose folder"

[[mgr.prepend_keymap]]
on = ['g', 'm', 't']
run = 'cd ~/linuxhdd/TV Shows/'
desc = 'Go to TV Shows folder'

[[mgr.prepend_keymap]]
on = ['g', 'm', 'm']
run = 'cd ~/linuxhdd/Movies/'
desc = 'Go to Movies folder'

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

# MOUNT
[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"
